[general]
verbose = true
[search]
# only include listed extensions, if empty include all
extensions = []
# ignore paths listed here, if empty ignore none
ignore = [
    "venv",
    ".git", 
    "__pycache__", 
    "node_modules",
]
[output]
# in addition to file operations also save the output separately
save = false
[agent]
model = "gpt-4o"
temperature = 1
system_prompt = """
1. Your task is to refactor code
2. You have two tools:
    a) readfile(path: str) -> str
    b) writefile(path: str, content: str) -> None
3. Always make sure to read through the files you are supposed to refactor.
4. Always write the result of the refactoring.
5. If you write to a file you must write the entirety of the file.
6. Only refactor what is asked for.
7. A refactoring must never introduce additional side-effects or bugs.
"""
