[general]
verbose = true
write_reference = true
[search]
extensions = [".js"]
ignore = [
    "venv",
    ".git", 
    "__pycache__", 
    "node_modules", 
    "coverage", 
    "skivvy_tests", 
    "migrations",
    "eslintrc"]

[agent]
model = "gpt-4o-2024-11-20"
temperature = 1
system_prompt = """
1. Your task is to refactor code
2. You accomplish this by writing the refactored code to files.
3. If you write to a file you must write entirety of the file.
4. Only refactor what is asked for.
5. A refactoring must never introduce additional side-effects or bugs.
"""
